### ISSUE TITLE
Position controller not responding to topic: position_hold/trajectory

### ISSUE THREAD

**Issue by luccagandra** [larics/icuas22_competition#5]
After publishing a message to topic position_hold/trajectory, the drone does not responds to the commands sent to it. Echo of the message sent:

The drone is at start position, hovering in the air.

What can I do? Also, does the controller only works after True is published on topic challenge_started?

```
header: 
  seq: 1
  stamp: 
    secs: 170
    nsecs: 428000000
  frame_id: "world"
joint_names: []
points: 
  - 
    transforms: 
      - 
        translation: 
          x: 4.463480957993883
          y: -3.5185942793974228
          z: 0.9937927619095479
        rotation: 
          x: 0.0
          y: 0.0
          z: 0.14325704124905955
          w: 0.989685515773857
    velocities: 
      - 
        linear: 
          x: 0.3975676177011968
          y: 0.110301838990751
          z: 0.047554655736897475
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
    accelerations: 
      - 
        linear: 
          x: -1.6803622346025018
          y: -0.3780814806255524
          z: -0.10390202681597333
        angular: 
          x: 0.0
          y: 0.0
          z: 0.0
    time_from_start: 
      secs: 0
      nsecs:         0
---

```
